<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>CRUD MVC</title>
        <link rel="stylesheet" href="assets/styles/css/style.css" />
    </head>
    <body>
        <header>
            <nav>
                <a href="index.php">Liste des utilisateurs</a>
                <a href="index.php?route=create_user">Créer un utilisateur</a>
            </nav>
        </header>
        <?php require "templates/$template.phtml"; ?>
    </body>
</html>