<main>
    <h1>Créer un utilisateur</h1>
    <form method="post" action="index.php?route=check_create_user">
        <fieldset>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" required />
        </fieldset>
        <fieldset>
            <label for="first_name">Prénom</label>
            <input type="text" id="first_name" name="first_name" required />
        </fieldset>
        <fieldset>
            <label for="last_name">Nom</label>
            <input type="text" id="last_name" name="last_name" required />
        </fieldset>
        <button type="submit">Créer</button>
    </form>
</main>