<main>
    <h1>Modifier un utilisateur</h1>
    <form method="post" action="index.php?route=check_update_user">
        <input type="hidden" name="id" value="<?= $data["user"]->getId() ?>" />
        <fieldset>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" value="<?= $data["user"]->getEmail() ?>" required />
        </fieldset>
        <fieldset>
            <label for="first_name">Prénom</label>
            <input type="text" id="first_name" name="first_name" value="<?= $data["user"]->getFirstName() ?>" required />
        </fieldset>
        <fieldset>
            <label for="last_name">Nom</label>
            <input type="text" id="last_name" name="last_name" value="<?= $data["user"]->getLastName() ?>" required />
        </fieldset>
        <button type="submit">Modifier</button>
    </form>
</main>